# Spam or not spam

In [5]:
import numpy as np
import pandas as pd
import string

df = pd.read_csv("data.csv")
df.head(30)

text  spam
0   Subject: naturally irresistible your corporate...     1
1   Subject: the stock trading gunslinger  fanny i...     1
2   Subject: unbelievable new homes made easy  im ...     1
3   Subject: 4 color printing special  request add...     1
4   Subject: do not have money , get software cds ...     1
5   Subject: great nnews  hello , welcome to medzo...     1
6   Subject: here ' s a hot play in motion  homela...     1
7   Subject: save your money buy getting this thin...     1
8   Subject: undeliverable : home based business f...     1
9   Subject: save your money buy getting this thin...     1
10  Subject: las vegas high rise boom  las vegas i...     1
11  Subject: save your money buy getting this thin...     1
12  Subject: brighten those teeth  get your  teeth...     1
13  Subject: wall street phenomenon reaps rewards ...     1
14  Subject: fpa notice : ebay misrepresentation o...     1
15  Subject: search engine position  be the very f...     1
16  Subject: only our software is guaranteed 100 %...     1
17  Subject: localized software , all languages av...     1
18  Subject: security alert - confirm your nationa...     1
19  Subject: 21 st century web specialists jrgbm  ...     1
20  Subject: any med for your girl to be happy !  ...     1
21  Subject: re : wearable electronics  hi my name...     1
22  Subject: top - level logo and business identit...     1
23  Subject: your trusted source for prescription ...     1
24  Subject: rely on us for your online prescripti...     1
25  Subject: guzzle like a fountain  spur m rocks ...     1
26  Subject: are you losing ? the answer would ama...     1
27  Subject: hi  how to save o improper n your med...     1
28  Subject: 25 mg did thhe trick  ho receivable w...     1
29  Subject: save your money buy getting this thin...     1

In [6]:
df.shape

(5728, 2)

In [7]:
df.columns

Index(['text', 'spam'], dtype='object')

In [8]:
df.drop_duplicates(inplace=True)
print(df.shape)

(5695, 2)


In [10]:
print(df.isnull().sum())

text    0
spam    0
dtype: int64


In [12]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\eZee\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
def process(text):
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)

    clean = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    return clean
# to show the tokenization
df['text'].head().apply(process)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
message = CountVectorizer(analyzer=process).fit_transform(df['text'])

In [15]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(message, df['spam'], test_size=0.20, random_state=0)
print(message.shape)

(5695, 37229)


In [16]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(xtrain, ytrain)

In [17]:
print(classifier.predict(xtrain))

[0 0 0 ... 0 0 0]


In [18]:
print(ytrain.values)

[0 0 0 ... 0 0 0]


In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(xtrain)
print(classification_report(ytrain, pred))
print()
print("Confusion Matrix: \n", confusion_matrix(ytrain, pred))
print("Accuracy: \n", accuracy_score(ytrain, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix: 
 [[3445   12]
 [   1 1098]]
Accuracy: 
 0.9971466198419666


In [20]:
#print the predictions
print(classifier.predict(xtest))
#print the actual values
print(ytest.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(xtest)
print(classification_report(ytest, pred))
print()
print("Confusion Matrix: \n", confusion_matrix(ytest, pred))
print("Accuracy: \n", accuracy_score(ytest, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix: 
 [[862   8]
 [  1 268]]
Accuracy: 
 0.9920983318700615
